### ISSUE TITLE
How to test the trained model on image?

### ISSUE THREAD

**Issue by nile649** [zwenaing/unsupervised-image-segmentation#1]
I have trained the model, and now I wish to test the image with it, 

Thanks

**Comment by zwenaing** [comment]
I haven't looked into the details of evaluation. You can check the paper
here https://arxiv.org/abs/1711.08506
Best of luck,
- Zwe

*Zwe Naing*
*Northeastern University MSCS Class of 2019*
*College of Computer and Information Sciences*
Linkedin <http://linkedin.com/in/zwenaing>

**Comment by zwenaing** [comment]
I haven't looked into the details of evaluation. You can check the paper here https://arxiv.org/abs/1711.08506. Best of luck
